from __future__ import annotations

DEFAULT_WIDTH = 800
DEFAULT_HEIGHT = 600
DEFAULT_BACKGROUND = "#FFFFFF"
DEFAULT_MAX_ITERATIONS = 25
DEFAULT_PROVIDER = "anthropic"
DEFAULT_MAX_OUTPUT_TOKENS = 4096
DEFAULT_THINKING_BUDGET = 4096
DEFAULT_EXPORT_SCALE = 2.0
